version: "3"
services:
  web:
    build:
     context: .
     dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./webapp:/opt/webapp
  db:
    env_file: .env
    build:
      context: ./src/main/docker/db/
    ports:
      - "5431:5432"
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
