@startuml


class Game {

__
GameStatus

EndingCriteria
(GameTitle)
(GameDescription)
GameStartTime
GameEndTime
 }

Game "n" *-- "PlayerCount" Player: PlayingOrder

Game "1" *-- "1" Player: GameInitiator

Game "1" o-- "PlayerCount" Story: StoryList

class Player {
__
Email
(NickName)
}


class Story {
___
StoryStatus

}

Story "1"--"1" Player: CurrentPlayer


Story "1" *-- "n" Part
class Part {

__
Line1
Line2
Line3

}

Part "1" <-- "1" Player : Writer

class Turn {

}



@enduml